<?php

use Vit\Doctor\Helper;

$APPLICATION->IncludeComponent('bitrix:news.list', 'vd-reviews', [
    'ACTIVE_DATE_FORMAT' => 'j.m.Y',
    'ADD_SECTIONS_CHAIN' => 'N',
    'AJAX_MODE' => 'N',
    'AJAX_OPTION_ADDITIONAL' => '',
    'AJAX_OPTION_HISTORY' => 'N',
    'AJAX_OPTION_JUMP' => 'N',
    'AJAX_OPTION_STYLE' => 'N',
    'CACHE_FILTER' => 'N',
    'CACHE_GROUPS' => 'N',
    'CACHE_TIME' => '36000000',
    'CACHE_TYPE' => 'A',
    'CHECK_DATES' => 'Y',
    'DETAIL_URL' => '',
    'DISPLAY_BOTTOM_PAGER' => 'N',
    'DISPLAY_DATE' => 'Y',
    'DISPLAY_NAME' => 'N',
    'DISPLAY_PICTURE' => 'N',
    'DISPLAY_PREVIEW_TEXT' => 'N',
    'DISPLAY_TOP_PAGER' => 'N',
    'FIELD_CODE' => [],
    'FILE_404' => '',
    'FILTER_NAME' => '',
    'HIDE_LINK_WHEN_NO_DETAIL' => 'N',
    'IBLOCK_ID' => Helper::getIblockIdByCode('vd-reviews'),
    'IBLOCK_TYPE' => 'vd_reviews',
    'INCLUDE_IBLOCK_INTO_CHAIN' => 'N',
    'INCLUDE_SUBSECTIONS' => 'Y',
    'MESSAGE_404' => '',
    'NEWS_COUNT' => '10',
    'PAGER_BASE_LINK_ENABLE' => 'N',
    'PAGER_DESC_NUMBERING' => 'N',
    'PAGER_DESC_NUMBERING_CACHE_TIME' => '',
    'PAGER_SHOW_ALL' => 'N',
    'PAGER_SHOW_ALWAYS' => 'N',
    'PAGER_TEMPLATE' => '',
    'PAGER_TITLE' => '',
    'PARENT_SECTION' => '',
    'PARENT_SECTION_CODE' => '',
    'PREVIEW_TRUNCATE_LEN' => '',
    'PROPERTY_CODE' => ['NAME', 'GRADE', 'TYPE', 'VIDEO', 'PLATFORM', 'PLATFORM_LINK'],
    'SET_BROWSER_TITLE' => 'N',
    'SET_LAST_MODIFIED' => 'N',
    'SET_META_DESCRIPTION' => 'N',
    'SET_META_KEYWORDS' => 'N',
    'SET_STATUS_404' => 'N',
    'SET_TITLE' => 'N',
    'SHOW_404' => 'N',
    'SORT_BY1' => 'ACTIVE_FROM',
    'SORT_BY2' => '',
    'SORT_ORDER1' => 'DESC',
    'SORT_ORDER2' => '',
    'STRICT_SECTION_CHECK' => 'N'
]); ?>